---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
configMapGenerator:
  - name: customresourcestate-metrics
    files:
      - customresourcestate-metrics.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
- podmonitor.yaml
