{
 "title": "Crossplane / Resource / Monitoring",
 "tags": [
  "crossplane",
  "orange",
  "claim"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "claim_namespace",
    "query": {
     "query": "label_values(kube_customresource_condition_status,claim_namespace)"
    }
   },
   {
    "name": "claim_name",
    "query": {
     "query": "label_values(kube_customresource_condition_status{claim_namespace=\"$claim_namespace\"},claim_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster-wide monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total ready object",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count_values(\"count\", kube_customresource_condition_status{type=\"Ready\"} == 1) by (claim_namespace)",
     "legendFormat": "{{claim_namespace}}"
    }
   ]
  },
  {
   "title": "Total non-ready object",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "count_values(\"count\", kube_customresource_condition_status{type=\"Ready\"} == 0) by (claim_namespace)",
     "legendFormat": "{{claim_namespace}}"
    }
   ]
  },
  {
   "title": "Total ready object",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", kube_customresource_condition_status{type=\"Ready\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total unready object",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", kube_customresource_condition_status{type=\"Ready\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total synced object",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count_values(\"count\", kube_customresource_condition_status{type=\"Synced\"} == 1) by (claim_namespace)",
     "legendFormat": "{{claim_namespace}}"
    }
   ]
  },
  {
   "title": "Total non-synced object",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "count_values(\"count\", kube_customresource_condition_status{type=\"Synced\"} == 0) by (claim_namespace)",
     "legendFormat": "{{claim_namespace}}"
    }
   ]
  },
  {
   "title": "Total synced object",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", kube_customresource_condition_status{type=\"Synced\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total unsynced object",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "!" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", kube_customresource_condition_status{type=\"Synced\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace $claim_namespace monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Ready claim object",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kube_customresource_condition_status{type=\"Ready\"} == 1",
     "legendFormat": "{{claim_name}}"
    }
   ]
  },
  {
   "title": "Non-ready claim object",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "kube_customresource_condition_status{type=\"Ready\"} == 0",
     "legendFormat": "{{claim_name}}"
    }
   ]
  },
  {
   "title": "Synced claim object",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_customresource_condition_status{type=\"Synced\"} == 1",
     "legendFormat": "{{claim_name}}"
    }
   ]
  },
  {
   "title": "Non-synced claim object",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "kube_customresource_condition_status{type=\"Synced\"} == 0",
     "legendFormat": "{{claim_name}}"
    }
   ]
  }
 ]
}