{
 "title": "Crossplane / Provider",
 "description": "Provider-IAAS dashboard for operator monitoring",
 "tags": [
  "crossplane",
  "provider-iaas",
  "orange"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "resource",
    "query": {
     "query": "label_values(apiserver_request_duration_seconds_bucket,group)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{pod=\"$pod\"},controller)"
    }
   },
   {
    "name": "controller_resource",
    "label": "controller equivalent K8s",
    "query": {
     "query": "label_values(apiserver_storage_objects{resource=~\".*$resource\"},resource)"
    }
   }
  ]
 },
 "panels": [
  { "title": "K8s API Server for $resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read SLI - Requests (Global API Server)",
   "type": "timeseries",
   "description": "How many read requests (LIST,GET) per second do the apiservers get by code?",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"read\"})",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Write SLI - Requests (Global API Server)",
   "type": "timeseries",
   "description": "How many write requests (POST|PUT|PATCH|DELETE) per second do the apiservers get by code?",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"write\"})",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "API request duration for $resource (95th)",
   "type": "timeseries",
   "description": "Response latency distribution in seconds for each verb, dry run value, group, version, resource, subresource, scope and component.",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(apiserver_request_duration_seconds_bucket{component=\"apiserver\",group=~\".*$resource\"}) by (verb, le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API request rate for $resource",
   "type": "timeseries",
   "description": "Rate counter of apiserver requests broken out for each verb, dry run value, group, version, resource, scope, component, and HTTP response code.",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{component=\"apiserver\",group=~\".*$resource\"}[$__rate_interval])) by (verb) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count resource in ETCd",
   "type": "timeseries",
   "description": "Number of stored objects at the time of last check split by kind.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=~\".*$resource\"}) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Compute Resources - Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage per container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\"}) by (container)",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Memory Usage (WSS) per container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}\n)\n",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}\n)\n",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} - Receive"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} - Transmit"
      }
     ]
    },
    {
     "title": "Rate of Received Packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} - Receive"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} - Transmit"
      }
     ]
    }
   ]
  },
  { "title": "Crossplane - Provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Runtime Reconcile rate",
   "type": "timeseries",
   "description": "Rate of reconciliations per controller.",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{pod=\"$pod\"}[$__rate_interval])) by (controller)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GoRoutines",
   "type": "stat",
   "description": "Number of running GoRoutines for ",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_goroutines{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Golang version",
   "type": "stat",
   "description": "Information about the Go environment.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In use memory",
   "type": "stat",
   "description": "Number of bytes allocated and still in use.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "OS Thread",
   "type": "stat",
   "description": "Number of OS threads created.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_threads{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Runtime reconcile error rate",
   "type": "timeseries",
   "description": "Error rate of reconciliations per controller.",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{pod=\"$pod\", result=\"error\"}[$__rate_interval])) by (controller)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Allocated memory",
   "type": "stat",
   "description": "Total number of bytes allocated, even if freed.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(go_memstats_alloc_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "File description",
   "type": "stat",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_open_fds{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Allocated objects",
   "type": "stat",
   "description": "Number of allocated objects.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_objects{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "CPU time consumption",
   "type": "stat",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Controller Workers",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(controller_runtime_active_workers{namespace=\"$namespace\", pod=\"$pod\"}) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(controller_runtime_max_concurrent_reconciles{namespace=\"$namespace\", pod=\"$pod\"}) by (controller)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_errors_total{namespace=\"$namespace\", pod=\"$pod\"}[$__range])) by (controller)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_errors_total{namespace=\"$namespace\", pod=\"$pod\"}[$__range])) by (controller)/sum(increase(controller_runtime_reconcile_total{namespace=\"$namespace\", pod=\"$pod\"}[$__range])) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage metadata",
   "type": "stat",
   "description": "Number of bytes used for garbage collection system metadata.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_gc_sys_bytes{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Client API Request Rate",
   "type": "timeseries",
   "description": "Number of HTTP requests, partitioned by status code, method, and host.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{pod=\"$pod\",code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{pod=\"$pod\",code=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{pod=\"$pod\",code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{pod=\"$pod\",code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "description": "Rate number of adds handled by workqueue.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{pod=\"$pod\"}[$__rate_interval])) by (name) * 60",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "description": "Current depth of workqueue.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(workqueue_depth{pod=\"$pod\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency (95th)",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket{pod=\"$pod\"}[$__rate_interval])) by (name, le))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Retries",
   "type": "timeseries",
   "description": "Rate number of retries handled by workqueue",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(workqueue_retries_total{pod=\"$pod\"}[$__rate_interval]) * 60",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Crossplane - Provider resource - $controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }
  },
  {
   "title": "Runtime Reconcile rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{pod=\"$pod\", controller=\"$controller\"}[$__rate_interval])) by (result) *60",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reconcialiation loop waiting time",
   "type": "timeseries",
   "description": "Maximum time taken by the provider to cover all managed resources",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$Number/$Rate", "type": "math" }
   ]
  },
  {
   "title": "Controller Reconcile Total",
   "type": "stat",
   "description": "Total number of reconciliations per controller since last provider startup",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{namespace=\"$namespace\", pod=\"$pod\",controller=\"$controller\"}[$__range])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Reconcile duration heatmap",
   "type": "heatmap",
   "description": "Length of time per reconciliation per controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "increase(controller_runtime_reconcile_time_seconds_bucket{namespace=\"$namespace\", pod=\"$pod\", controller=\"$controller\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue duration heatmap",
   "type": "heatmap",
   "description": "How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "increase(workqueue_queue_duration_seconds_bucket{namespace=\"$namespace\", pod=\"$pod\", name=\"$controller\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}