apiVersion: dns.gcp.upbound.io/v1beta1
kind: RecordSet
metadata:
  name: benchmarkthree-aruma{{.numId}}-{{.Iteration}}
  labels:
    source: kube-burner
spec:
  forProvider:
    managedZone: aruma-zone-dns{{.numId}}
    name: benchmarkthree-{{.Iteration}}.aruma{{.numId}}.orange.com.
    rrdatas:
      - 127.0.0.1
    ttl: 300
    type: A
