{
 "title": "1- Kubebench",
 "tags": [ "kubebench" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Created keypair (K8s API)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "apiserver_request_total{code=\"201\", resource=\"recordsets\", service=\"kubernetes\"} - (apiserver_request_total{code=\"201\", resource=\"recordsets\", service=\"kubernetes\"} @ start())",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Delete keypair (K8s API)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "apiserver_request_total{resource=\"recordsets\", verb=\"DELETE\", service=\"kubernetes\", code=\"200\"} - (apiserver_request_total{resource=\"recordsets\", verb=\"DELETE\", service=\"kubernetes\", code=\"200\"} @ start())",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage (by namespace)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Number of log - Request Async Create (Provider GCP-DNS)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count_over_time({pod=~\"provider-gcp-dns-.+\"} |= `DNS Record create request:` [$__range])"
    }
   ]
  },
  {
   "title": "Number of log - Request Success Create (Provider GCP-DNS)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "count_over_time({pod=~\"provider-gcp-dns-.+\"} |= `Async create ended.` [$__range])"
    }
   ]
  },
  {
   "title": "Memory Usage (by namespace)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Number of log - Request Async Delete (Provider GCP-DNS)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({pod=~\"provider-gcp-dns-.+\"} |= `Async delete starting...` [$__range])"
    }
   ]
  },
  {
   "title": "Number of log - Request Success Delete (Provider GCP-DNS)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({pod=~\"provider-gcp-dns-.+\"} |= `Successfully deleted managed resource` [$__range])"
    }
   ]
  },
  {
   "title": "CPU Utilisation (Node 1 master)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node-exporter\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Read SLI - Requests (API Server)",
   "type": "graph",
   "description": "How many read requests (LIST,GET) per second do the apiservers get by code?",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"read\", cluster=\"$cluster\"})",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Write SLI - Requests (API Server)",
   "type": "graph",
   "description": "How many write requests (POST|PUT|PATCH|DELETE) per second do the apiservers get by code?",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"write\", cluster=\"$cluster\"})",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "CPU Usage on crossplane-system",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"crossplane-system\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"crossplane-system\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"crossplane-system\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Utilisation (Node 1 Master)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Number of object K8s cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 19 },
   "targets": [
    {
     "expr": "topk(3, apiserver_storage_objects)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate (API Server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"apiserver\", cluster=\"$cluster\"}[$__rate_interval])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "RAM Usage on crossplane-system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"crossplane-system\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Utilisation (Node 1 Master)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate5m{job=\"node-exporter\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Receive"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate5m{job=\"node-exporter\", instance=\"10.1.243.37:9100\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Error line in GCP-DNS provider",
   "type": "logs",
   "gridPos": { "h": 19, "w": 20, "x": 4, "y": 27 },
   "targets": [
    {
     "expr": "{pod=~\"provider-gcp-dns-.+\"} |= `error`"
    }
   ]
  },
  {
   "title": "Disk IO Utilisation (Node 1 Master)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_seconds:rate5m{job=\"node-exporter\", cluster=\"$cluster\"} != 0",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Utilisation (Node 1 master)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(1 -\n  (\n   max without (mountpoint, fstype) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", cluster=\"\", device=\"/dev/vda1\"})\n   /\n   max without (mountpoint, fstype) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", cluster=\"\", device=\"/dev/vda1\"})\n  ) != 0\n)\n\n",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}